= 15 DOMAIN SERVICE RESOURCE

A domain service is a well-known (singleton) domain object that typically acts as a repository and/or factory, providing actions for obtaining other domain object instances (although services can provide any kind of functionality in relation to objects).

Domain services can be accessed from the object list representation xref:section-b/chapter-11.adoc[§B11] returned by the GET Domain Services resource xref:section-b/chapter-07.adoc[§B7].

[#_15_1_http_get]
== 15.1 HTTP GET

Obtain summary representation of a domain service..
The endpoint URL for this resource is:
/services/{serviceId}
where:

* {serviceId} is a unique identifier for the service

=== 15.1.1 Request

==== 15.1.1.1 Query String

* x-ro-domain-model (optional, xref:section-a/chapter-03.adoc#_3_1_domain_metadata_x_ro_domain_model[§A3.1])


** "simple"


** "formal"

==== 15.1.1.2 Headers

* *Accept*


** application/json


** application/json;profile=".../object"

==== 15.1.1.3 Body

* N/A

=== 15.1.2 Success Response

As per xref:section-c/chapter-13.adoc#_13_1_request_succeeded_and_generated_a_representation[§C13.1] (200), returning a domain object representation xref:section-c/chapter-14.adoc#_14_4_representation[§C14.4].
